# BEGIN_KITTY_THEME
# Miko
include miko.conf
# END_KITTY_THEME

font_family      CozetteVector Nerd Font
bold_font        CozetteVector Nerd Font
italic_font      CozetteVector Nerd Font
bold_italic_font CozetteVector Nerd Font
font_size 13.0
background_opacity 0.9
