$image = {{image}}
<* for name, value in colors *>
${{name}} = rgba({{value.default.hex_stripped}}ff)
${{name}}_90 = rgba({{value.default.hex_stripped}}e6)
${{name}}_80 = rgba({{value.default.hex_stripped}}cc)
${{name}}_60 = rgba({{value.default.hex_stripped}}99)
${{name}}_40 = rgba({{value.default.hex_stripped}}66)
${{name}}_30 = rgba({{value.default.hex_stripped}}4d)
${{name}}_25 = rgba({{value.default.hex_stripped}}40)
${{name}}_20 = rgba({{value.default.hex_stripped}}33)
${{name}}_15 = rgba({{value.default.hex_stripped}}26)
<* endfor *>
