# miko palette

background      = 0xFF0F0F1A
base            = 0xFF151524
text            = 0xFFE8E8E8
alternate_base  = 0xFF2D2D44
bright_text     = 0xFFFFD0DD
link_text       = 0xFF9966CC
accent          = 0xFFFFB7C5
accent_secondary = 0xFF9966CC

rounding_large  = 10
rounding_small  = 5

font_family            = CozetteVector
font_family_monospace  = CozetteVector
