include themes/Matugen.conf

font_family      RobotoMono Nerd Font
italic_font      RobotoMono Nerd Font
bold_italic_font RobotoMono Nerd Font
font_size 13.0
background_opacity 0.9

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME